[general]
name = "hashmap"
version = "1.0.0"

[build]
files = ["hashmap.fix"]

[build.test]
files = ["test.fix"]


[[dependencies]]
name = "hash"
version = "1.0.0"
git = { url = "https://github.com/tttmmmyyyy/fixlang-hash.git" }
